version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 17092003
      PGDATA: /var/lib/postgresql/data/pgdata/


  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db

